training:
  episodes: 50000
  render_every: 100        
  save_model: true
  resume_training: true
  resume_model_path: "best_model_score_70.pth"
  render_video: false
  
wandb:
  use_wandb: false         
  project_name: "Snake-DQN"
  run_name: "Reinforced_Snake_Training"