_wandb:
    value:
        cli_version: 0.26.1
        e:
            o6bqox5yjq48ld8ryuozpijd52sm8b7t:
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "499428188160"
                        used: "282756505600"
                email: piotrhirkyj@gmail.com
                executable: C:\Users\vvv\AppData\Local\Programs\Python\Python312\python.exe
                git:
                    commit: 3f7ebe4b74afc7b48ffaceb0f14f9b8c942001b4
                    remote: https://github.com/ibtyog/Reinforced-snake.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-07484af4-0cf7-272e-307b-dd30449d2ea6
                host: DESKTOP-4LVB809
                memory:
                    total: "34294743040"
                os: Windows-10-10.0.19045-SP0
                program: -m train
                python: CPython 3.12.6
                root: C:\Users\vvv\Desktop\RL Snake
                startedAt: "2026-05-09T10:23:32.742609Z"
                writerId: o6bqox5yjq48ld8ryuozpijd52sm8b7t
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.6
            "5": 0.26.1
            "8":
                - 3
            "12": 0.26.1
            "13": windows-amd64
agent:
    value:
        batch_size: 64
        epsilon_decay: 0.995
        epsilon_min: 0.01
        epsilon_start: 1
        gamma: 0.9
        learning_rate: 0.001
        memory_size: 100000
env:
    value:
        base_height: 20
        base_width: 20
        expand_every: 5
        green_apple_prob: 0.3
rewards:
    value:
        death: -100
        green_apple: 20
        life_penalty: -0.1
        red_apple: 10
training:
    value:
        episodes: 500
        render_every: 10
        save_model: true
wandb:
    value:
        project_name: Snake-DQN
        run_name: test_run_1
        use_wandb: true
